name: Create new Release

on:
  workflow_dispatch:
    inputs:
      boomerang-version:
        description: Version of https://github.com/akamai/boomerang for which an SBOM should be built and released. Needs to match the version's tag.
        type: string
        required: true

jobs:
  build-and-release:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: 'akamai/boomerang'
          ref: ${{ github.event.inputs.boomerang-version }}
      - name: Build plugin
        run: |
          npm install grunt
          grunt clean build
      - name: Prepare SBOM generation
        run: mkdir boomerang-sboms
      - name: Generate XML SBOM
        uses: CycloneDX/gh-node-module-generatebom@master
        with:
          output: ./boomerang-sboms/boomerang-sbom.xml
      - name: Generate JSON SBOM
        uses: CycloneDX/gh-node-module-generatebom@master
        with:
          output: ./boomerang-sboms/boomerang-sbom.json
          json: true
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.boomerang-version }}
          files: boomerang-sboms/*
